# fly.toml app configuration file generated for my-chatgpt-retrieval-plugin on 2024-01-04T23:30:02+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-chatgpt-retrieval-plugin"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
